comment out

diff --git a/.github/workflows/client-build.yml b/.github/workflows/client-build.yml
--- a/.github/workflows/client-build.yml
+++ b/.github/workflows/client-build.yml
@@ -197,35 +197,35 @@ jobs:
           sudo apt update -y
           sudo apt install -y postgresql-client
 
-      # Create a run record exactly at the time of merge to release to
-      # ensure we compare run details with code at this point
-      - name: Create Perf Meta
-        if: steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
-        continue-on-error: true
-        run: |
-          PGPASSWORD='${{secrets.APPSMITH_PERFORMANCE_DB_PASSWORD}}' psql -h '${{secrets.APPSMITH_PERFORMANCE_DB_HOST}}' \
-          -U aforce_admin -d perf-infra -c \
-          "INSERT INTO public.run_meta (repo, gh_run_id, gh_run_attempt, is_active)
-          VALUES ('${{github.repository}}', '${{github.run_id}}', '${{github.run_attempt}}', FALSE)"
+      # # Create a run record exactly at the time of merge to release to
+      # # ensure we compare run details with code at this point
+      # - name: Create Perf Meta
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
+      #   continue-on-error: true
+      #   run: |
+      #     PGPASSWORD='${{secrets.APPSMITH_PERFORMANCE_DB_PASSWORD}}' psql -h '${{secrets.APPSMITH_PERFORMANCE_DB_HOST}}' \
+      #     -U aforce_admin -d perf-infra -c \
+      #     "INSERT INTO public.run_meta (repo, gh_run_id, gh_run_attempt, is_active)
+      #     VALUES ('${{github.repository}}', '${{github.run_id}}', '${{github.run_attempt}}', FALSE)"
 
-      # In case this is second attempt try restoring status of the prior attempt from cache
-      - name: Restore the previous run result
-        if: steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/run_result
-          key: ${{ github.run_id }}-${{ github.job }}-client
+      # # In case this is second attempt try restoring status of the prior attempt from cache
+      # - name: Restore the previous run result
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: |
+      #       ~/run_result
+      #     key: ${{ github.run_id }}-${{ github.job }}-client
 
-      # Fetch prior run result
-      - name: Get the previous run result
-        if: steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
-        id: run_result
-        run: cat ~/run_result 2>/dev/null || echo 'default'
+      # # Fetch prior run result
+      # - name: Get the previous run result
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
+      #   id: run_result
+      #   run: cat ~/run_result 2>/dev/null || echo 'default'
 
-      # In case of prior failure run the job
-      - if: steps.run_result.outputs.run_result != 'success' && (steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
-        run: echo "I'm alive!" && exit 0
+      # # In case of prior failure run the job
+      # - if: steps.run_result.outputs.run_result != 'success' && (steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
+      #   run: echo "I'm alive!" && exit 0
 
       - name: Use Node.js
         if: steps.run_result.outputs.run_result != 'success' && (steps.changed-files-specific.outputs.any_changed == 'true' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
